import path from "node:path";
import { defineConfig } from "vitest/config";
import { cloudflareTest, readD1Migrations } from "@cloudflare/vitest-pool-workers";

/**
 * Integration tests run inside a real Workers runtime (via Miniflare/
 * workerd) against a real local D1 database, rather than against a real
 * Postgres instance the way the old Express version's integration
 * suite did (see .github/workflows/ci.yml, which used to spin up a
 * postgres service container for this). D1's migrations (lib/db/migrations,
 * SQL generated by drizzle-kit) are read here at config-build time and
 * applied inside the workerd runtime by test/apply-migrations.ts before any
 * test runs - see that file for why the two steps are split.
 */
export default defineConfig(async () => {
  const migrationsPath = path.join(__dirname, "../../lib/db/migrations");
  const migrations = await readD1Migrations(migrationsPath);

  return {
    plugins: [
      cloudflareTest({
        wrangler: { configPath: "./wrangler.jsonc" },
        miniflare: {
          bindings: { TEST_MIGRATIONS: migrations },
        },
      }),
    ],
    test: {
      include: ["src/**/*.integration.test.ts"],
      setupFiles: ["./test/apply-migrations.ts"],
    },
  };
});
